version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:latest

jobs:
  
  check:
    executor: node
    steps:
      - checkout
      - run:
          name: â¬‡ï¸ Installing...
          command: yarn
      - run: 
          name: ğŸ Check formatting...
          command: .ci/check_formating.sh
      - run: 
          name: ğŸ“‹ Check linting...
          command: .ci/check_linting.sh
      - run: 
          name: ğŸ”³ Check types...
          command: .ci/check_types.sh
      - run: 
          name: âœ… Check tests...
          command: .ci/check_tests.sh

  build:
    executor: node
    steps:
      - checkout
      - run:
          name: â¬‡ï¸ Installing...
          command: yarn
      - run: 
          name: ğŸ— Building
          command: .ci/build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - check
      - build
