version: 2.1

orbs:
  percy: percy/agent@volatile

executors:
  node:
    docker:
      - image: circleci/node:latest-browsers

jobs:

  install:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: â¬‡ï¸ Installing...
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths: .

  check:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: â˜£ï¸ Check danger...
          command: .ci/check_danger.sh
      - run: 
          name: ğŸ Check formatting...
          command: .ci/check_formating.sh
      - run: 
          name: ğŸ“‹ Check linting...
          command: .ci/check_linting.sh
      - run: 
          name: ğŸ”³ Check types...
          command: .ci/check_types.sh
      - run: 
          name: âœ… Check tests...
          command: .ci/check_tests.sh

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: ğŸ— Building
          command: .ci/build.sh
      - persist_to_workspace:
          root: .
          paths: .

  snapshot:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: ğŸ“· Snapshotting
          command: .ci/snapshot.sh

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: ğŸš€ Deploy
          command: .ci/deploy.sh

  publish:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: â¬†ï¸ Publishing
          command: .ci/version_and_publish.sh

workflows:
  version: 2
  default:
    jobs:
      - install
      - check:
          requires: 
            - install
      - build:
          requires: 
            - install
      - snapshot:
          requires:
            - build
      
      - percy/finalize_all:
          requires:
            - snapshot
      - deploy:
          requires: 
            - check
            - build
            - snapshot
      - publish:
          requires: 
            - check
            - build
            - snapshot
          filters:
            branches:
              only:
                - master
