version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:latest

commands:
  install:
    description: "Install dependencies"
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: â¬‡ï¸ Installing...
          command: yarn
      - save_cache:
          name: Save Yarn Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:

  check:
    executor: node
    steps:
      - install
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: 
          name: ğŸ Check formatting...
          command: .ci/check_formating.sh
      - run: 
          name: ğŸ“‹ Check linting...
          command: .ci/check_linting.sh
      - run: 
          name: ğŸ”³ Check types...
          command: .ci/check_types.sh
      - run: 
          name: âœ… Check tests...
          command: .ci/check_tests.sh

  build:
    executor: node
    steps:
      - install
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: 
          name: ğŸ— Building
          command: .ci/build.sh

  publish:
    executor: node
    steps:
      - install
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: 
          name: â¬†ï¸ Publishing
          command: .ci/version_and_publish.sh

workflows:
  version: 2
  default:
    jobs:
      - check:
          requires: 
            - install
      - build:
          requires: 
            - install
      - publish:
          requires: 
            - install
            - check
            - build
          filters:
            branches:
              only:
                - master
